# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py

# Build settings
build:
  os: ubuntu-22.04
  image: "latest"
  tools:
     python: "3.9"

python:
  install:
    - requirements: requirements.txt

